### ISSUE TITLE
[SUGGESTION] can you please also add marker like shop bank where need to press E to access the menu other than command /atm

### ISSUE THREAD

**Issue by mr-capy** [qbcore-framework/qb-atms#26]
**Describe the feature you'd like**
Can you add a marker so no need to use command /atm just to go near atm the marker will show [E] and by button press we can access the atm

**Describe alternatives you've considered**
No alternative is suitable for this

**Comment by AlexR1712** [comment]
Hello @GhzGarage , a question why this Issue was closed if it seems that this functionality has not been implemented? 

Thank you very much in advance
