### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by Maureks** [qbcore-framework/qb-atms#30]
**Is your feature request related to a problem? Please describe.**
No problem just a sugestion 

**Describe the feature you'd like**
Is it posible, to make this script work with qb-target? Instead of players doing the /atm command in atm's props, to use qb-target to access atm's in the same way.   

**Describe alternatives you've considered**
Just this one
PS- I'am open to learn , if I have to do it 
**Additional context**
Thanks and sorry for the bad english! Good Holidays !

**Comment by DxMaxi** [comment]
Just add on qb-atms -> client.lua

```
exports['qb-target']:AddTargetModel(Config.ATMModels, {
    options = {
        {
            type = "command",
            event = "atm",
            icon = "fab fa-cc-visa",
            label = "Use ATM",
        },
    },
    distance = 1.0
})
```

**Comment by Maureks** [comment]
Thanks for the advice , instead of adding it to qb-atm , I added it to qb-target and it works really well , thank you so much ! 

For those who want to use atm's with qb-target , just add this to your qb-target/config.lua under Config.TargetModels :

	["Atm"] = {
		models = {"prop_atm_01","prop_atm_02","prop_atm_03","prop_fleeca_atm"},
		options = {
			{
				type = "command",
				event = "atm",
				icon = "fab fa-cc-visa",
				label = "Access ATM",
			}
		},
		distance = 2.5,
	},


Much thanks to DxMaxi for the help !!!! Nice holidays everyone !

**Comment by DxMaxi** [comment]
Yes its the same, but your welcome, happy holidays for you too
