### ISSUE TITLE
[BUG] doesn't start with server restart

### ISSUE THREAD

**Issue by parham-tehrani** [qbcore-framework/qb-atms#38]
i've set up the qb-atms to work with qb-target.
i've already ensured it on the server config
it works perfectly fine when the qb-target is off using the /atm command
however when i enable it to use with qb-target, on server restart, it doesn't work, and doesn't give any error.
once i restart the script manually, it starts working just fine without any issues.

**Comment by GhzGarage** [comment]
Try adding qb-target as a dependency in the fxmanifest or start qb-target before the [qb] folder and let me know if that fixes it

**Comment by erikmeyer08** [comment]
The target nor text ([E]) doesn't work for me and only /atm.

**Comment by Gangstaaaaa** [comment]
might be because you don't have a atm card in your inventory?

**Comment by SmokeSlickz** [comment]
if you dont have issues with any other target based interaction and still face issue on the atm alone, do consider trying to use it without any graphics mods like nve mod packs certain mods disable them frm interaction mentioned in bug #47
