### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by OutragedMetro** [qbcore-framework/qb-atms#47]
So I am using the qbcore ATM script with QBCORE but when you walk up to an ATM press alt or E nothing happens and I cannot use an atm I was wondering if you had a fix for this?

**Comment by xjacl87** [comment]
Try changing in config.lua this Config.UseTarget = GetConvar('UseTarget', 'false') == 'true' to this Config.UseTarget = 'true' its works fine to me and no errors.

**Comment by SmokeSlickz** [comment]
> Try changing in config.lua this Config.UseTarget = GetConvar('UseTarget', 'false') == 'true' to this Config.UseTarget = 'true' its works fine to me and no errors.

i did try that but still it just doesnt want to show up.

**Comment by charj** [comment]
Is this now resolved?

**Comment by SmokeSlickz** [comment]
> Is this now resolved?

so i did find out it was a graphics mod issue, Specifically the nve update where animated atms are brought in place, the animated atms add a layer to the existing atm which makes it not reachable by the qb target system.

**Comment by charj** [comment]
Can close.
