### ISSUE TITLE
[SUGGESTION] qb-atms correctif for ox_inventory

### ISSUE THREAD

**Issue by allChuu** [qbcore-framework/qb-atms#62]
**Is your feature request related to a problem? Please describe.**
Yes - Generated creditcard have an metadata issue with qb-atms and don't allow to use it.

**Describe the feature you'd like**
Using qb-banking & qb-atms with ox_inventory

**Additional context**
`[script:qb-atms] SCRIPT ERROR: @qb-atms/server/main.lua:76: attempt to index a nul value (local 'info')`

This error appear in fx consol when you try to target the ATM and "Use ATM".

**Comment by kompots** [comment]
+1
