### ISSUE TITLE
[BUG] ATMs not doing anything

### ISSUE THREAD

**Issue by PCL-CrisKolkman** [qbcore-framework/qb-atms#63]
**Describe the bug**
So you're able to get a card etc and banking is working fine, but when approaching an ATM nothing happens. No errors in F8 but you just cannot use ATMs at all.

**To Reproduce**
1. Go to any ATM

**Expected behavior**
Some message to press "E" to open ATM or use third-eye.

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: last week
 - Are you using custom resource? which ones? no
 - Have you renamed `qb-` to something custom? no

**Comment by GhzGarage** [comment]
You use the card

**Comment by PCL-CrisKolkman** [comment]
> You use the card

Ahhh that makes sense, thank you
